### ISSUE TITLE
auto-detect output file type rather than setting `plotdata.format`

### ISSUE THREAD

**Issue by rjleveque** [clawpack/visclaw#221] opened 2017-07-21 20:07 UTC
This should perhaps be done in pyclaw rather than visclaw.  

See the discussion at #220.

**Comment by brandon1780** [comment] 2017-07-24 07:59
Push

**Comment by brandon1780** [comment] 2017-07-24 08:04
#220

**Comment by brandon1780** [comment] 2017-07-24 08:05
Duplicate of #

**Comment by ketch** [comment] 2019-02-23 19:28
Update: #220 is closed; the relevant PR is https://github.com/clawpack/visclaw/pull/222.

**Closed** 2019-02-23 23:46 UTC
